apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: azureKeyVaultDemoDapr
    - name: azureEnvironment
      value: "AZUREPUBLICCLOUD"
    - name: azureTenantId
      value: "83f0ccab-3c6a-4564-b52e-878b50150717"
    - name: azureClientId #the Application ID of the app identity. Go to App Registrations in Azure Portal to create an app
      value: "79e3a7df-1c1e-45fe-9dd9-a4aa1a2392cc"
    - name: azureClientSecret #the secret used to request an authorization token for the app. Client Secrets can be defined under App Registrations > App Name > Certificates & secrets.
      value : "NvX8Q~DMv10TkEBZOjazdhIlL7du3wUiNwyIRb2i"

